// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnimedSiteLinksAPI.Data;

#nullable disable

namespace UnimedSiteLinksAPI.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnimedSiteLinksAPI.Moldes.UnimedLinksModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoDoSite")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("Descricao");

                    b.Property<string>("ImagemDoSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagem");

                    b.Property<string>("NomeDoSite")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Site");

                    b.Property<string>("UrlDoSite")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.ToTable("Sites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
